word_list =[
    'bollocks',
    'cheerio',
    'crikey',
    'cheers',
    'blimey',
    'chuffed',
    'chin up',
    'gday mate',
    'bonza',
    'beaut',
    'ripper',
    'struth',
    'arvo',
    'strewth',
    'heinous',
    'hoser',
    'hadding',
    'wean',
    'oot',
    'lassie',
    'laddie',
    'aye',
    'baldy',
    'eejit',
    'stoatin']